### ISSUE TITLE
Could not create container due to slow download from tinycore repository

### ISSUE THREAD

**Issue by lucribas** [gpdm/tinycore-targetdisplaymode#6]
Due to the slow download of the tinycore repository, I was unable to successfully create the container.

Error example:
cursesw.tcz          96% |******************************  |  203k  0:00:00 ETA
ncursesw.tcz          96% |******************************  |  203k  0:00:00 ETA
ncursesw.tcz          96% |******************************  |  203k  - stalled -
ncursesw.tcz          96% |******************************  |  203k  - stalled -
ncursesw.tcz          96% |******************************  |  203k  - stalled -
ncursesw.tcz          96% |******************************  |  203k  - stalled -
ncursesw.tcz          96% |******************************  |  203k  - stalled -
wget: download timed out
md5sum: WARNING: 1 of 1 computed checksums did NOT match
ncursesw.tcz: FAILED
Error on ncursesw.tcz

Maybe I can change wget flags?

**Comment by lucribas** [comment]
For me that PR fixed the slow internet. Maybe other users can set timeout to 100 or even 1000 seconds.

**Comment by gpdm** [comment]
Hi @lucribas 

Thank you for your contribution.

However I would like to not include this in `Dockerfile`by default, as it doesn't really address a real bug or malfunction in the TinyCore 'tce-load' command per se.

As I see it, it's a *workaround*, which addresses bad connectivity and timeout situations and makes it just work when you're running over an unreliable internet connection.

I would rather recommend, you contribute to the FAQ section, describing the issue, and the workaround properly there. Then people can decide themselves, if they need this when it's applicable or not.

In my opinion, it tries to address the issue "unreliable downloads" from the wrong end.

If the root cause is "The TinyCore repositories are slow/unreliable", then the TinyCore people should actually fix the repository (proof needed!).
I personally don't believe, this is the case.

Rather likely, the root cause is "The internet connection is slow/unreliable", then just patching the `tce-load` temporarily in a downstream project like mine, is likewise wrong.
It "fixes" it just for this particular project.

But many actual TinyCore users all over the world might be suffering from similar conditions coming over unreliable connections.
Hence it would be preferrable to then have the `tce-load` command extended with proper timeout support in the upstream code base.
So you should send the PR for the `tce-load` comand rather to the TinyCore project instead, so everyone could have a benefit from it.


For this reason, I'm rather in favor of saying that I would accept a PR from you with FAQ/documentational annotations, 
describing the issue and how to workaround the timeout situations.
But I would not accept a permanent code-patch, as it's "fixing from the wrong end".

Cheers,
GP

**Comment by lucribas** [comment]
Hi @gpdm ,
thank you very much for answering.
I totally agree with you. 
As soon as possible I will try to contribute with FAQ/documentational annotations.

best regards!
